config/routes.rb
# Edited 7/20/2019 by Kori Kuzma: Added resourcers for users, groups, members
Rails.application.routes.draw do
  resources :posts, :standard_posts, :group_posts
  resources :groups, :members, :comments, :workouts, :emoji_rating, :exercises, :cardios, :liftings
  root 'users#index'
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
end

app/models/workout.rb
# Created 7/11/2019 by Gilberto Molina Badillo
# Description: dependencies of workout

# Edited 7/17/2019 by Gilberto Molina Badillo
# removed date, made a table for it and created a dependency
class Workout < ApplicationRecord
  validates :name, presence: true, length: { in: 1..20 }
  belongs_to :user, foreign_key: 'username'
  has_many :exercises
  has_many :workout_whens
  accepts_nested_attributes_for :exercises
  validates :exercise, presence: true
end

app/controllers/workouts_controller.rb
class WorkoutsController < ApplicationController
  before_action :set_workout, only: [:show, :edit, :update, :destroy]

  # GET /workouts
  # GET /workouts.json
  def index
    @workouts = Workout.all
  end

  # GET /workouts/1
  # GET /workouts/1.json
  def show
  end

  # GET /workouts/new
  def new
    @workout = Workout.new
    @workout.exercises.build
  end

  # GET /workouts/1/edit
  def edit
    @workout.exercise.build
  end

  # POST /workouts
  # POST /workouts.json
  def create
    @workout = Workout.new(workout_params)

    respond_to do |format|
      if @workout.save && workout_params[:exercise].save
        format.html { redirect_to @workout, notice: 'Workout was successfully created.' }
        format.json { render :show, status: :created, location: @workout }
      else
        format.html { render :new }
        format.json { render json: @workout.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /workouts/1
  # PATCH/PUT /workouts/1.json
  def update
    respond_to do |format|
      if @workout.update(workout_params)
        format.html { redirect_to @workout, notice: 'Workout was successfully updated.' }
        format.json { render :show, status: :ok, location: @workout }
      else
        format.html { render :edit }
        format.json { render json: @workout.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /workouts/1
  # DELETE /workouts/1.json
  def destroy
    @workout.destroy
    respond_to do |format|
      format.html { redirect_to workouts_url, notice: 'Workout was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_workout
      @workout = Workout.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def workout_params
      params.fetch(:workout, {}).permit(:name, :username, exercise_attributes: [:reps, :set, :descriptions, :name, :author, :actable_id, :actable_type, :workout_id])
    end
end

app/helpers/workouts_helper.rb
module WorkoutsHelper
end

app/views/workouts/_form.html.erb
<%= form_with(model: workout, local: true) do |form| %>
  <% if workout.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(workout.errors.count, "error") %> prohibited this workout from being saved:</h2>

      <ul>
      <% workout.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<main class="centered" style=" border: 3px solid red; height: 100%; margin:0 20% 0 20%; padding: 0% 0% 40% 0%; background-color:#fffeee">
<div class="ui form">
  <div class="fields">
    <div class="field">
      <%= form.label :name %>
      <%= form.text_field :name %>
    </div>
    <div class="field">
      <%= form.label :username %>
      <%= form.text_field :username %>
    </div>

    <h2> Exercise Catagories </h2>
    <div class = "field">
    <%= form.fields_for :exercise do |exercise| %>
        <%= exercise.label :reps %>
        <%= exercise.text_field :reps %>
        <%= exercise.label :sets %>
        <%= exercise.text_field :sets %>
    <% end %>
    </div>
</div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>
</main>

app/views/workouts/edit.html.erb
<h1>Editing Workout</h1>

<%= render 'form', workout: @workout %>

<%= link_to 'Show', @workout %> |
<%= link_to 'Back', workouts_path %>

app/views/workouts/index.html.erb
<p id="notice"><%= notice %></p>
<h1>Workouts</h1>
<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @workouts.each do |workout| %>
      <tr>
        <td><%= link_to 'Show', workout %></td>
        <td><%= link_to 'Edit', edit_workout_path(workout) %></td>
        <td><%= link_to 'Destroy', workout, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<%= link_to 'New Workout', new_workout_path %>

app/views/workouts/new.html.erb
<h1>Create New Workout</h1>

<%= render 'form', workout: @workout %>

<%= link_to 'Back', workouts_path %>

app/views/workouts/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_workout_path(@workout) %> |
<%= link_to 'Back', workouts_path %>