config/routes.rb
# Edited 7/20/2019 by Kori Kuzma: Added resourcers for users, groups, members
Rails.application.routes.draw do
  resources :posts, :standard_posts, :group_posts
  resources :groups, :members, :comments, :workouts, :emoji_rating, :exercises, :cardios, :liftings
  root 'users#index'
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
end

app/models/group_post.rb
# Created 7/20/2019 by Nick Hackman
# Edited 7/22/2019 by Nick Hackman, adding multi table inheritance
# Description: GroupComment Class
class GroupPost < ApplicationRecord
  belongs_to :group
  acts_as :post
end

app/controllers/group_posts_controller.rb
# Created 7/22/2019 by Nick Hackman
# Description: Controller for Standard Post
class GroupPostsController < ApplicationController
  before_action :set_group_post, only: %i[show destroy]

  # GET /group_posts/:id
  # GET /group_posts/:id.json
  def show
    @group_post = GroupPost.find params[:id]
  end

  # GET /group_posts/new
  def new
    @group_post = GroupPost.new
  end

  # POST /group_posts
  # POST /group_posts.json
  def create
    params = group_post_params
    params[:username] = current_user.username
    @group_post = GroupPost.new params
    respond_to do |format|
      if @group_post.save
        format.html { redirect_to @group_post, notice: 'Group post was successfully created.' }
        format.json { render :show, status: :created, location: @group_post }
      else
        format.html { render :new }
        format.json { render json: @group_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /group_posts/:id
  # DELETE /group_posts/:id.json
  def destroy
    @group_post.destroy
    respond_to do |format|
      format.html { redirect_to group_posts_url, notice: 'Group post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_group_post
    @group_post = GroupPost.find params[:id]
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def group_post_params
    params.fetch(:group_post, {}).permit :content, :comments
  end
end

app/helpers/group_posts_helper.rb
module GroupPostsHelper
end

app/views/group_posts/_form.html.erb
<%= form_with(model: group_post, local: true) do |form| %>
  <% if group_post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(group_post.errors.count, "error") %> prohibited this group_post from being saved:</h2>
      <ul>
      <% group_post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%attrib = %i[content]%>
  <main class="centered">
    <div class="ui form">
      <div class="fields">
        <%attrib.each do |attribute| %>
          <div class="field">
            <%= form.label attribute %>
            <%= form.text_field attribute %>
          </div>
        <%end%>
      </div>
    </div>
  </main>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/group_posts/edit.html.erb
<h1>Editing Group Post</h1>

<%= render 'form', group_post: @group_post %>

<%= link_to 'Show', @group_post %> |
<%= link_to 'Back', group_posts_path %>

app/views/group_posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Group Posts</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @group_posts.each do |group_post| %>
      <tr>
        <td><%= link_to 'Show', group_post %></td>
        <td><%= link_to 'Edit', edit_group_post_path(group_post) %></td>
        <td><%= link_to 'Destroy', group_post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Group Post', new_group_post_path %>

app/views/group_posts/new.html.erb
<h1>New Group Post</h1>

<%= render 'form', group_post: @group_post %>

<%= link_to 'Back', group_posts_path %>

app/views/group_posts/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_group_post_path(@group_post) %> |
<%= link_to 'Back', group_posts_path %>